# Generated by Django 4.1.2 on 2022-10-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کنسرت')),
                ('singer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خواننده')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان کنسرت')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='concert_images/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت ها',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محل برگزاری')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس محل برگزاری')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن محل برگزاری')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='ظرفیت محل برگزاری')),
            ],
            options={
                'verbose_name': 'مکان برگزاری کنسرت',
                'verbose_name_plural': 'مکان های برگزاری کنسرت',
            },
        ),
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع کنسرت')),
                ('seats', models.IntegerField(blank=True, null=True, verbose_name='تعداد صندلی')),
                ('status', models.IntegerField(blank=True, choices=[('start', 'فروش بلیط شروع شده است'), ('end', 'فروش بلیط تمام شده است'), ('canceled', 'این سانس کنسل شده است'), ('on_sale', 'در حال فروش بلیط')], null=True, verbose_name='وضعیت')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.concertmodel', verbose_name='نام کنسرت')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.locationmodel', verbose_name='محل برگزاری کنسرت')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('ticket_img', models.ImageField(blank=True, null=True, upload_to='ticket_images/', verbose_name='عکس')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel', verbose_name='نام کاربر مرتبط')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_sales.timemodel', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط ها',
            },
        ),
    ]
